### PR TITLE
 Unpacking returned array from pervious step to arguments for next step if next_step.arity == array.count

### PR DESCRIPTION
**Pull request by zhulik**
Unused code and dependency removed. Rubocop fixes.

### CODE REVIEW

**Comment by guzart** [comment]
Hi @zhulik! Thank you very much for the needed cleanup and the argument unpacking functionality. 

I need to think more about this. On one hand, one of the things that make Ruby so wonderful is how convenient it is, but on the other hand too much magic is confusing. 

Returning an array from the previous step could be used as a tuple, not necessarily as multiple arguments for the next array. I think it would be much clearer if there was a way/option to make this functionality explicit.

**Comment by zhulik** [comment]
I think, it's obvious and intuitive that step which has few arguments should receive that arguments not as an array. Anyway it's possible to add some kind of helper method for this.

**Comment by guzart** [comment]
Hey! I really like your approach on handling failures. 

Any reason why you close the PR?

**Comment by zhulik** [comment]
I have forgotten about the PR and continued development as I want. I'm not sure that you like everything I changed. Check out my fork, maybe we can continue together

**Comment by guzart** [comment]
Well, as you can see there's very little code here and the project is in its infancy. I am very glad that you are doing some real work on this. My goal for opie was to reduce the magic/convention and make it more explicit, that's why I hesitated adding the array unboxing.

fwiw: I started this gem inspired by [Trailblazer's flow control](http://trailblazer.to/gems/operation/2.0/index.html#flow-control), and some ideas from [dry-matcher](http://dry-rb.org/gems/dry-matcher/) and [dry-monads](http://dry-rb.org/gems/dry-monads/). 

I look forward to learn from your work and the API you develop.

**Pull request closed without merging**
